### ISSUE TITLE
Erori de conexiune mongodb

### ISSUE THREAD

**Issue by rellyrayssa** [gosocial-romania/gosocialdev#1]
Am facut ceva greseli cred, ca atunci cand incerc sa introduc un produs in dashboard nu il salveaza 'database error conection'

**Comment by pixeldublu** [comment]
Verifica consola sa nu iti fi crapat ceva...
Sau poate nu ai pornit mongo ... dar atunci nu cred ca mai ajungeai in dashboard.

**Comment by rgolea** [comment]
Buna! Pentru a porni server-ul este nevoie de [mongodb](https://www.mongodb.org/downloads#production) si dupa ce este instalat trebuie sa creezi un folder
Windows - [Windows](https://docs.mongodb.org/manual/tutorial/install-mongodb-on-windows/):
```
C:\data\db\
```
Mac sau Linux - [OSX](https://docs.mongodb.org/manual/tutorial/install-mongodb-on-os-x/) - [Linux](https://docs.mongodb.org/manual/administration/install-on-linux/)
```
/data/db/
```
Poti vedea documentatia mai sus.
Dupa ce ai facut foler-ul va trebui sa setezi permisiunile. (Deschis pentru toata lumea)
Windows
```
> C:
> chmod -R 0777 /data/
```
MacOSX - Linux
```
$ cd /
$ sudo chmod -R 777 /data/
```
E posibil sa ai probleme de permisiuni cu consola cmd. Nu prea am multa experienta cu ea. Iti recomand consola de pe sourcetree fiind consola bash. (Poti instala una si de [aici](https://git-scm.com/download/win)). Prin ea, poti executa comenzi de OSX si Linux pe Windows.

Odata terminat, cauta in `Program Files` sau `Program Files x86`, in folder-ul `\mongo\bin` sau in `mongo`, arhiva `mongod.exe`. Adauga daca stii la PATH ca sa fie mai usoara lansarea printr-un simplu:
Windows
```
> mongod
```
MacOSX - Linux
```
$ sudo mongod
```

**Comment by rellyrayssa** [comment]
Stiam eu ca trebuie sa creez niste fisiere ,dar nu-mi mai aduceam aminte ce si cum. Mersi mult!

**Comment by rgolea** [comment]
Nu ai pentru ce! Abia astept sa vad modificari :)
