### ISSUE TITLE
Grunt sau gulp?

### ISSUE THREAD

**Issue by bogdan2510** [gosocial-romania/gosocialdev#8]
Salutare.
Pana la urma ce o sa folosim, grunt sau Gulp? @rgolea

**Comment by rgolea** [comment]
@bogdan2510 ar fi bine Gulp. E mai rapid pe windows. Incearca sa il configurezi si sa lasi o arhiva `CONTRIBUTING.md` cu niste guidelines in care sa vedem structura proiectului, etc.

**Comment by bogdan2510** [comment]
Hmmm.
Nu am folosit niciodata gulp.
Incerc sa-l configurez si revin.

**Comment by rgolea** [comment]
Daca nu, configureaza Grunt si restul proiectului, fiind bine comentat Grunt si vom muta pe Gulp saptamana viitoare. Asa putem studia ambele.

**Comment by bogdan2510** [comment]
Ok. Grunt sa fie.
