### ISSUE TITLE
folosim jade?

### ISSUE THREAD

**Issue by bogdan2510** [gosocial-romania/gosocialdev#9]
Salutare tuturor.
## Sunteti de acord sa folosim jade?

mai multe informatii despre jade gasiti aici:  http://jade-lang.com/

**Comment by rgolea** [comment]
Eu consider ca ar fi bine. Atat [jade](http://jade-lang.com) cat si [sass](http://sass-lang.com) sau [less](http://lesscss.org). De tinut cont ca bootstrap 3 foloseste less si bootstrap 4 (cand va iesi) foloseste sass

**Comment by bogdan2510** [comment]
jade este la devDependencies?

**Comment by rgolea** [comment]
Deobicei da. Ideea e ca in `devDependencies` avem tot ceeace ajuta sa genereze un css/html/js normal si care, odata ce e generat nu mai e de refolosit.
